In [94]:
import numpy as np
from StringIO import StringIO
import string
from scipy import stats
from sklearn import datasets, linear_model
import math

In [123]:
data = np.genfromtxt('movie_metadata.csv', dtype=None, delimiter=',', autostrip=True)
data = np.delete(data, [2, 7, 10, 11, 12, 15, 17, 18, 22], 1)
colNames = data[0,:]
movieData = np.delete(data, (0), axis=0)
numMovies = movieData.shape[0]
print numMovies 

5041


In [127]:
def easydex(MovieRow, FeatureString):
   
   MovieRow = MovieRow -1
   my_data_dict= {}
   
   col_names = data[0,:]
   
   if FeatureString != 0:
       for l in range(0,28):
           my_data_dict[col_names[l]]= data[1:,l]
   
   
       example1 = my_data_dict[FeatureString]
       return[example1[MovieRow]]
   
   else:
       my_data_neat_index = data[1:,:]
       myMovieSample = my_data_neat_index[MovieRow,:]
       return myMovieSample

In [128]:
genres = {'Action', 'Adventure','Animation','Biography','Comedy','Crime','Documentary','Drama','Family','Fantasy',
          'Film-Noir','Game-Show','History','Horror','Music','Musical','Mystery','News','Reality-TV','Romance','Sci-Fi',
          'Short','Sport','Thriller','War','Western'}

moviesByGenreBucket = {}

for genre in genres:
    moviesByGenreBucket[genre] = []
    

In [129]:
# Normalize the data 
#stats.zscore(movieData)

In [130]:
for movie in movieData:    
    localGenres = string.split(movie[10], "|")
    for genre in localGenres:
        #print "adding movieID = %s to genre bucket %s" % (movie[0], genre)
        moviesByGenreBucket[genre].append(movie[0])
        
    if movie[1] == 'Color':
        movie[1] = 1
    else:
        movie[1] = 0

KeyError: '0'

In [131]:
#for key in moviesByGenreBucket.keys():
    #print "%s = %s" % (key, len(moviesByGenreBucket[key]))

#print moviesByGenreBucket['Game-Show']
#movieData[0:113, 1]

In [132]:
# remove cols like names
movieData = np.delete(movieData, [2, 7, 10, 11, 12, 15, 17, 18, 22], 1)
print movieData.shape
print 

(5041, 12)



In [133]:
# Split data into Test, Train
dataSplitRate = 0.7
numSamples = int(math.floor(numMovies * dataSplitRate))
train = movieData[:numSamples]
test = movieData[numSamples:]
trainX = np.delete(train, 26, axis=1)
trainY = train[:,26]
testX = np.delete(test, 26, axis=1)
testY = test[:,26]

IndexError: index 26 is out of bounds for axis 1 with size 12

In [134]:
# linear regression
regr = linear_model.LinearRegression()
regr.fit(trainX, trainY)

ValueError: could not convert string to float: James Cameron

In [135]:
arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print (arr)
print np.delete(arr, [0,2], 1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]
